package com.orbis.app.data

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * One row per app per day. Written by the usage-tracking layer (Phase 1) and
 * read by both the dashboard and the throttle-intensity ranking.
 *
 * The unique index is what makes re-running a refresh idempotent: without it,
 * `OnConflictStrategy.REPLACE` has only the autogenerated id to match on and
 * every refresh would append a duplicate row.
 *
 * `date` leads it deliberately. SQLite can only use an index whose *leading*
 * column is constrained, so with `app` first the dashboard's
 * `WHERE date BETWEEN ?` scanned the whole table - which grows by four rows a
 * day forever. This ordering serves the range query and the uniqueness
 * constraint at once.
 */
@Entity(
    tableName = "usage_log",
    indices = [Index(value = ["date", "app"], unique = true)],
)
data class UsageLog(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    /** Package name, e.g. `com.instagram.android`. */
    val app: String,
    /** ISO-8601 local date, `yyyy-MM-dd`. */
    val date: String,
    val durationMillis: Long,
)
