package com.orbis.app.data

import androidx.room.Room
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class UsageLogDaoTest {

    private lateinit var database: OrbisDatabase
    private lateinit var dao: UsageLogDao

    @Before
    fun setUp() {
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        database = Room.inMemoryDatabaseBuilder(context, OrbisDatabase::class.java).build()
        dao = database.usageLogDao()
    }

    @After
    fun tearDown() {
        database.close()
    }

    @Test
    fun refreshingTheSameDayReplacesRatherThanDuplicates() = runBlocking {
        // Guards the unique (app, date) index. Without it, REPLACE has only the
        // autogenerated id to match on and every refresh appends a new row.
        dao.upsert(UsageLog(app = "com.instagram.android", date = "2026-07-29", durationMillis = 60_000L))
        dao.upsert(UsageLog(app = "com.instagram.android", date = "2026-07-29", durationMillis = 90_000L))

        val rows = dao.observeForDate("2026-07-29").first()

        assertEquals(1, rows.size)
        assertEquals(90_000L, rows.single().durationMillis)
    }

    @Test
    fun sameAppOnDifferentDaysKeepsSeparateRows() = runBlocking {
        dao.upsert(UsageLog(app = "com.instagram.android", date = "2026-07-28", durationMillis = 60_000L))
        dao.upsert(UsageLog(app = "com.instagram.android", date = "2026-07-29", durationMillis = 30_000L))

        assertEquals(1, dao.observeForDate("2026-07-28").first().size)
        assertEquals(1, dao.observeForDate("2026-07-29").first().size)
    }

    @Test
    fun observeForDateOrdersByDurationDescending() = runBlocking {
        dao.upsert(UsageLog(app = "com.whatsapp", date = "2026-07-29", durationMillis = 10_000L))
        dao.upsert(UsageLog(app = "com.instagram.android", date = "2026-07-29", durationMillis = 99_000L))
        dao.upsert(UsageLog(app = "com.snapchat.android", date = "2026-07-29", durationMillis = 50_000L))

        val apps = dao.observeForDate("2026-07-29").first().map { it.app }

        assertEquals(
            listOf("com.instagram.android", "com.snapchat.android", "com.whatsapp"),
            apps,
        )
    }

    @Test
    fun forDateRangeSpansInclusiveBounds() = runBlocking {
        dao.upsert(UsageLog(app = "com.instagram.android", date = "2026-07-27", durationMillis = 1_000L))
        dao.upsert(UsageLog(app = "com.instagram.android", date = "2026-07-28", durationMillis = 2_000L))
        dao.upsert(UsageLog(app = "com.instagram.android", date = "2026-07-29", durationMillis = 3_000L))

        val inRange = dao.forDateRange("2026-07-27", "2026-07-28")

        assertEquals(2, inRange.size)
        assertEquals(3_000L, inRange.sumOf { it.durationMillis })
    }
}
